INSERT into ACCOUNT(ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_TYPE,AMOUNT) values ('Account1','user1','wallet',1500);
INSERT into ACCOUNT(ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_TYPE,AMOUNT) values ('Account2','user2','wallet',1500);
INSERT into ACCOUNT(ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_TYPE,AMOUNT) values ('Account3','user3','wallet',1500);
INSERT into ACCOUNT(ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_TYPE,AMOUNT) values ('Account4','user4','wallet',1500);